// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhrluvhbajdsnmvnpjzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocmx1dmhiYWpkc25tdm5wanprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjQyMDgsImV4cCI6MjA2MDU0MDIwOH0.NdOp3KzvRjzUxbeAHW8ylFCHcec3FDM2345TpZSP_EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);